version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "9000:9000"
    environment:
      - DATABASE_URL=postgresql://product_user:product_pass@postgres:5432/product_db
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: product_db
    environment:
      POSTGRES_USER: product_user
      POSTGRES_PASSWORD: product_pass
      POSTGRES_DB: product_db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
