version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    container_name: product_db
    environment:
      POSTGRES_USER: product_user
      POSTGRES_PASSWORD: product_pass
      POSTGRES_DB: product_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U product_user -d product_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: