# https://hub.docker.com/_/postgres

version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: product_db
    environment:
      POSTGRES_USER: product_user
      POSTGRES_PASSWORD: product_pass
      POSTGRES_DB: product_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: