name: Backend - Compile and Test
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Setup sbt
        uses: sbt/setup-sbt@v1
        with:
          sbt-version: "1.9.8"

      - name: Build and Test The project
        run: |
          cd backend
          sbt compile test