name: Frontend - Compile
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install
        run: |
          cd frontend
          npm install
          
      - name: compile
        run: |
          cd frontend
          npm run build